name: Publish Docker
# Controls when the action will run. 
on:
    # Triggers the workflow on push or pull request events but only for the main branch
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Publish to Registry
      uses: dyohan9/test-github-actions@main
      with:
        name: dyohan9/test-github-actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build Docker image for PRs
    #     run: |
    #       cd /tmp/build-pr
    #       LOWERCASE_REPOSITORY=$(echo "${{ github.repository_owner }}" | tr "[:upper:]" "[:lower:]")
    #       #IMAGE_NAME="ghcr.io/${LOWERCASE_REPOSITORY}/rocket.chat:pr-${{ github.event.number }}"
    #       echo "Build official Docker image ${IMAGE_NAME}"
    #       docker build -f $GITHUB_WORKSPACE/Dockerfile -t $IMAGE_NAME .
    #       docker push $IMAGE_NAME
