name: Build docker image

on:
    push:
    branches:
    - main

    tags:
    - '*'

    pull_request:

env:
    RUBY30: 3.0.1
    RUBY27: 2.7.3
    RUBY26: 2.6.7
    RUBY25: 2.5.9
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
    ruby30:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-buildx-action@v1
    - uses: ./.github/actions
        with:
        version: ${{ env.RUBY30 }}
        tags: 3.0,3,latest