# Automated pipeline for building and uploading autograder container images to Docker Hub.
#
# Jad Chaar <jadchaar@umich.edu>

name: upload-ag-images

on:
  push:
    branches:
      - main

jobs:
  upload-base:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Only rebuild if base image has changed
      - name: Build and push base Docker image
        uses: docker/build-push-action@v2
        with:
          context: base
          tags: dyohan9/test-github-actions:latest
          push: true

